### ISSUE TITLE
Update lab directors on website

### ISSUE THREAD

**Issue by jrddunbr** [COSI-Lab/cslabs#1]
Update lab director information on COSI website.

It doesn't even look like the HTML has been updated in this repository or I'd git-blame it.

http://cosi.clarkson.edu/contact.html

**Comment by reecer62** [comment]
It looks like some information does need to get updated in addition to lab director contacts, I will file a separate issue for general information

**Comment by jrddunbr** [comment]
https://github.com/COSI-Lab/cslabs/blob/a04adddef39cfcc8f522fc7482dbf041d83c461a/contact.html#L125
