### ISSUE TITLE
Add link to source code

### ISSUE THREAD

**Issue by Alextopher** [COSI-Lab/cslabs#8]
At the bottom of the page we should link to this repo.

**Comment by Phil94comp** [comment]
Which page do you want the link for the repo to be added to?

**Comment by Alextopher** [comment]
Every page in the footer section

**Comment by Alextopher** [comment]
Are you a COSI member / Clarkson student? If you're interested in a slightly larger project you can check out #7. Adding a proper templating system or modern JS library would make this change (and future changes) easier.

**Comment by Phil94comp** [comment]
I'm not a COSI member and I am not a Clarkson student. I am a new grad who is looking to make a first contribution on GitHub.

**Comment by Alextopher** [comment]
Cool :smile: https://goodfirstissue.dev/ is a cool resource. If you would like to contribute to our site feel free, no one else is currently working on it.

**Comment by Phil94comp** [comment]
Sorry I didn't write a comment sooner on the "Add link to source code" issue. I opened a pull request with the changes I made that included the link to the repo. Please let me know if this is what you are looking for or would you like for me to do something different.
